config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  get 'home/index'
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!


  private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_sign_up_path_for(resource)
    edit_user_path(current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_params, only: %i[show edit update destroy]

  def index
    @users = User.all.order(name: "ASC")
  end

  def show
  end

  def edit
  end

  def update
    @user.update(user_params)
    flash[:notice] = "User with email #{@user.email} updated"
    redirect_to user_path(@user)
  end

  def destroy
    @user.destroy
    flash[:alert] = "User with email #{@user.email} deleted"
    redirect_to users_path
  end


  private

  def set_params
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :gender, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.slim
section.hero.is-fullheight
  .hero-body
    .container
      .has-text-centered
        h1.title.is-1
          | Welcome Home#index 

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta content="width=device-width, initial-scale=1" name="viewport"
    title
      | Crudapp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    link href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css" rel="stylesheet" /
    script defer="" src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"
  body
    - if user_signed_in?
      = render "layouts/shared/navbar"
    = render "layouts/shared/notify" 
    = yield

app/views/layouts/shared/_navbar.html.slim
nav.navbar.is-warning aria-label=("main navigation") role="navigation" 
  .navbar-brand
    a.navbar-item href="/" 
      h1.title.is-4 Crud App
    a.navbar-burger.burger aria-expanded="false" aria-label="menu" data-target="navbarBasicExample" role="button" 
      span aria-hidden="true" 
      span aria-hidden="true" 
      span aria-hidden="true" 
  #navbarBasicExample.navbar-menu
    .navbar-start
      - if user_signed_in?
        = link_to "Home", home_index_path, class: "navbar-item"
        = link_to "List Users", users_path, class: "navbar-item"
    .navbar-end
      .navbar-item
        .buttons
        - if user_signed_in?
          = link_to "Log out", destroy_user_session_path, method: :delete, class: "button is-danger is-small"

app/views/layouts/shared/_notify.html.erb
<% unless flash.empty? %>
	<script>
      <% flash.each do |key, value| %>
      	<% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      	new Noty ({
          type: '<%= type %>',
          layout: 'topRight',
          timeout: '3000',
          theme: 'sunset',
          text: '<%= value %>'
        }).show();
      <% end %>
	</script>
<% end %>

app/views/users/edit.html.slim
section
  .hero-body
    .container
      .columns.is-centered
        .column.is-6-table.is-6-desktop.is-6-widescreen
          = form_for @user do |f|
            .card-content
              p.title.is-4 Edit User
              .field
                = f.label :name, class: "label"
                .control
                  = f.text_field :name, autofocus: true, autocomplete: "name", class: "input"
              .field
                = f.label :geder, class: "label"
                .control
                  .select
                    = f.select :gender, [['Female', 'female'], ['Male', 'male']], prompt: "Choose Gender"
              .field
                = f.label :address, class: "label"
                .control
                  = f.text_area :address, autofocus: true, autocomplete: "address", class: "input"
              .field
                .control
                  button.button.is-primary.is-small.is-rounded Submit

app/views/users/index.html.slim
.card-content
  h1.title.is-5 List Users
  table.table.is-hoverable.is-bordered.is-fullwidth
    thead
      tr
        th No
        th Name
        th Email
        th Address
        th.has-text-centered Action
    tbody
    - @users.each_with_index do |user, index|
      tr
        td #{index + 1}
        td #{user.name}
        td #{user.email}
        td #{user.address}
        td.has-text-centered
          = link_to "Detail", user_path(user), class: "button is-small is-info"
          |&nbsp;
          = link_to "Edit", edit_user_path(user), class: "button is-small is-primary"
          |&nbsp;
          - unless current_user == user
            = link_to "Delete", user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: "button is-small is-danger"

app/views/users/show.html.slim
section
  .hero-body
    .container
      .columns.is-centered
        .column.is-6-table.is-6-desktop.is-6-widescreen

          h1.title.is-4 Detail User
          h1.title.is-5 Name :
          h1.subtitle.is-5= @user.name
          hr
          h1.title.is-5 Email :
          h1.subtitle.is-5= @user.email
          hr
          h1.title.is-5 Gender :
          h1.subtitle.is-5= @user.gender
          hr
          h1.title.is-5 Address :
          h1.subtitle.is-5= @user.address
          hr
          =link_to "Edit", edit_user_path(@user), class: "button is-small is-primary is-rounded"